### ISSUE TITLE
Honor hitting ESC in all GUIs

### ISSUE THREAD

**Issue by Zidane** [AlmuraDev/Guide#2]
If ESC is pressed, close the GUI without processing any save logic.

**Comment by Grinch** [comment]
Escape is honored already due to it being a screen. If you are in a textfield it will leave that field again and hitting escape another time will close the screen.

**Comment by Dockter** [comment]
We should have a way to detect unsaved changed.  Easiest way is to have a hidden text box with the exact same data the guide text box has and then compare on close.  If they mismatch then display a confirmation window before respecting ESC key.

**Comment by Zidane** [comment]
Un-needed to have a hidden box (really @mcsnetworks ...) as the GUI has a copy of the Page that is within the client's PageRegistry. Simply need to do an equals check :P .

I smell some foxpro being attempted here.

**Comment by Dockter** [comment]
@Zidane I use the tools I had available....

**Comment by Grinch** [comment]
The initial issue was in valid and will stay closed. New issue for requested feature has been opened #14
