### ISSUE TITLE
Guides not reaching client with in server/client environment

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Guide#5]
Tested tonight, guides get pushed to the server but the client isn't getting the saved text of the guide itself.

Also has an issue where I logged into the server and it didn't send any of the guides to the client.

No errors on server or client.

**Comment by Dockter** [comment]
The list of guides usually loads but never the data from it.

**Comment by Grinch** [comment]
Is it all guides that show up? Anything in one of the guides triggering an exception? Try catching a throwable where we load the guides and see if anything shows up.
