### ISSUE TITLE
Blinking Cursor is at the wrong position

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Guide#7]
The longer you type in a text box the worse the issue becomes.  What happens is that the blinking cursor graphic starts to appear before the spot your typing at.

Tested with "Almura Preferred Font.zip" texture pack / font from our public repo

**Comment by Grinch** [comment]
Try testing with default font please.

**Comment by Dockter** [comment]
http://www.almuramc.com/images/GuideError3.png

**Comment by Dockter** [comment]
Default font works fine, which mean issue is within MalisisCore and calculating its font and string width with custom fonts.

**Comment by Grinch** [comment]
Correct. Poke Ordi for this.
